##===- lib/Makefile ----------------------------*- Makefile -*-===##

LEVEL=..

LIBRARYNAME=Fixpoint

LOADABLE_MODULE=1

SOURCES=FixpointSSI.cpp

DIRS=RangeAnalysis Transformations

CXX.Flags += -Wnon-virtual-dtor 

include $(LEVEL)/Makefile.common
