##===- lib/RangeAnalysis/Makefile ---------*- Makefile -*-===##

LEVEL=../..

LIBRARYNAME=RangeAnalysis

LOADABLE_MODULE=1

SOURCES= BaseRange.cpp Range.cpp RangePass.cpp WrappedRange.cpp

CXX.Flags += -Wnon-virtual-dtor 
include $(LEVEL)/Makefile.common
