##===- lib/Makefile ----------------------------*- Makefile -*-===##

LEVEL=..

LIBRARYNAME=Fixpoint

LOADABLE_MODULE=1

SOURCES=FixpointSSI.cpp

DIRS=RangeAnalysis Transformations

include $(LEVEL)/Makefile.common
